### ISSUE TITLE
Recorded file's duration is zero [m4a format, aacLc]

### ISSUE THREAD

**Issue by arreshashikant** [llfbandit/record#253] opened 2023-12-08 06:31 UTC
**Package version**
record: ^5.0.1

**Environment**
 - OS: Android 10, Redmi Note 8

**Describe the bug**

Recording works fine. But, when we try to get the duration of recorded file (either through [ffmpeg](https://pub.dev/packages/ffmpeg_kit_flutter) or [audioplayers](https://pub.dev/packages/audioplayers) plugin), it returns Zero Duration.

RecordConfig - Default
```
  const RecordConfig({
    this.encoder = AudioEncoder.aacLc,
    this.bitRate = 128000,
    this.sampleRate = 44100,
    this.numChannels = 2,
    this.device,
    this.autoGain = false,
    this.echoCancel = false,
    this.noiseSuppress = false,
  });
```

**To Reproduce**

Sample repository - 
https://github.com/arreshashikant/buggy_repo/tree/recordDurationZero
branch - `recordDurationZero`

**Expected behavior**
Return valid duration of the recorded file

**Additional context**
The recorded bytes returns valid duration if we start recording with `startStream`

**Comment by Hatemsla** [comment] 2023-12-10 16:49
Same problem

**Comment by arsyad-revo** [comment] 2023-12-13 09:49
I'm having the same issue too...
hopefully, it can be fixed soon...

**Comment by llfbandit** [comment] 2023-12-14 20:24
Released in record_android 1.0.4.

**Comment by Evgentret** [comment] 2023-12-20 04:46
Still have a problem with zero record duration, record_android 1.04

**Comment by llfbandit** [comment] 2023-12-20 22:18
This issue is very unclear to me. I don't reproduce any issue with the duration.
@arreshashikant Your reproducer is wrongly set, this is not how audioplayers works. You must rely on streams to get your info.

I updated the example in the repository to show the audio duration before playing it.

If other participants have more or other info to share, it is time before I close this.

**Comment by arreshashikant** [comment] 2023-12-21 01:49
I agree that we should rely on streams to get duration. But,
There's no issue with player when `AudioPlayer.getDuration()` call is made after `setSource` future is complete.

**Comment by Evgentret** [comment] 2024-01-02 10:41
> This issue is very unclear to me. I don't reproduce any issue with the duration. @arreshashikant Your reproducer is wrongly set, this is not how `audioplayers` works. You must rely on streams to get your info.
> 
> I updated the example in the repository to show the audio duration before playing it.
> 
> If other participants have more or other info to share, it is time before I close this.

When compile and build your example I've got duration 00:00:00.023 on Android real device in any way.
But when I run this example on iPhone - duration is correct.
Also, all audio recorded using iPhone had correct duration when playing in Android and all audio recorded in Android has near-the-zero duration in iPhone. 
Another example, when I send recorded audio by your example to the Telegram, if audio from iPhone - it has correct duration, when I send recorded audio from Android - duration showed zero.

Flutter (Channel stable, 3.16.5, on macOS 13.6.1 22G313 darwin-x64)

**Comment by Allenxuxu** [comment] 2024-01-17 12:43
I have the same issue.

**Comment by utkudenis** [comment] 2024-02-15 13:16
We had similar issue with player new version 5.0.x 
everyting is perfect 4.4.4 
however, when we updated to 5.0.x  there was unstable problem. although records can listen on the recorded phone. they were not working other devices. 
An Example,  recorder settings screenshot 
![image](https://github.com/llfbandit/record/assets/68633376/a6f00b85-0f66-4f56-8a3a-7b0f057295c1)

We used ai to compare working and notworking voice record. 
![image](https://github.com/llfbandit/record/assets/68633376/924e1f35-aba1-41d0-9fda-54af5421ab97)

The problem was on the bitrate. 

Summary, records on the android was problematic.  
file extension was .m4a

**Comment by blok5025** [comment] 2024-02-19 03:16
> We had similar issue with player new version 5.0.x everyting is perfect 4.4.4 however, when we updated to 5.0.x there was unstable problem. although records can listen on the recorded phone. they were not working other devices. An Example, recorder settings screenshot ![image](https://private-user-images.githubusercontent.com/68633376/305084166-a6f00b85-0f66-4f56-8a3a-7b0f057295c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTI2NTEsIm5iZiI6MTcwODMxMjM1MSwicGF0aCI6Ii82ODYzMzM3Ni8zMDUwODQxNjYtYTZmMDBiODUtMGY2Ni00ZjU2LThhM2EtN2IwZjA1NzI5NWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAzMTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiOGFkNTgyMzgzNzM0ZGVjYjc0MWYwNzZkOGY1YTcxZDdjYTk4Mjc0NGIxYjRlNmI1MzFlMjg5ZWE4OTM1YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mel9dm7dglD_j4hnT9-IBpSQvDA-_XpgGAKxkbiyMIM)
> 
> We used ai to compare working and notworking voice record. ![image](https://private-user-images.githubusercontent.com/68633376/305084576-924e1f35-aba1-41d0-9fda-54af5421ab97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTI2NTEsIm5iZiI6MTcwODMxMjM1MSwicGF0aCI6Ii82ODYzMzM3Ni8zMDUwODQ1NzYtOTI0ZTFmMzUtYWJhMS00MWQwLTlmZGEtNTRhZjU0MjFhYjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAzMTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZDAwYTE2ZDkzZTcxZDljOWJkNTU4Y2JiNmQwMTBkNGQ5NzJjYzkxNmJhM2EzNDEzMmY3YTI2NTZkNDA3OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1MSff-Ud8yTl3kF0pXerZC0GA_ut9QqHU6kLXps2d-Q)
> 
> The problem was on the bitrate.
> 
> Summary, records on the android was problematic. file extension was .m4a

Did you find a Solution?

I have an issue where files recorded on Android don't have an extension but can be listened on the device it was recorded but not on iOS

**Comment by utkudenis** [comment] 2024-02-20 11:17
> > We had similar issue with player new version 5.0.x everyting is perfect 4.4.4 however, when we updated to 5.0.x there was unstable problem. although records can listen on the recorded phone. they were not working other devices. An Example, recorder settings screenshot ![image](https://private-user-images.githubusercontent.com/68633376/305084166-a6f00b85-0f66-4f56-8a3a-7b0f057295c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTI2NTEsIm5iZiI6MTcwODMxMjM1MSwicGF0aCI6Ii82ODYzMzM3Ni8zMDUwODQxNjYtYTZmMDBiODUtMGY2Ni00ZjU2LThhM2EtN2IwZjA1NzI5NWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAzMTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiOGFkNTgyMzgzNzM0ZGVjYjc0MWYwNzZkOGY1YTcxZDdjYTk4Mjc0NGIxYjRlNmI1MzFlMjg5ZWE4OTM1YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mel9dm7dglD_j4hnT9-IBpSQvDA-_XpgGAKxkbiyMIM)
> > We used ai to compare working and notworking voice record. ![image](https://private-user-images.githubusercontent.com/68633376/305084576-924e1f35-aba1-41d0-9fda-54af5421ab97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTI2NTEsIm5iZiI6MTcwODMxMjM1MSwicGF0aCI6Ii82ODYzMzM3Ni8zMDUwODQ1NzYtOTI0ZTFmMzUtYWJhMS00MWQwLTlmZGEtNTRhZjU0MjFhYjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAzMTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZDAwYTE2ZDkzZTcxZDljOWJkNTU4Y2JiNmQwMTBkNGQ5NzJjYzkxNmJhM2EzNDEzMmY3YTI2NTZkNDA3OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1MSff-Ud8yTl3kF0pXerZC0GA_ut9QqHU6kLXps2d-Q)
> > The problem was on the bitrate.
> > Summary, records on the android was problematic. file extension was .m4a
> 
> Did you find a Solution?
> 
> I have an issue where files recorded on Android don't have an extension but can be listened on the device it was recorded but not on iOS

version 4.4.4.

**Comment by blok5025** [comment] 2024-02-20 16:59
@llfbandit This is a major issue as it's linked to the default settings of the RecordConfig(). Android files are corrupted and unreadable from the backend.

**Comment by blok5025** [comment] 2024-02-20 18:02
@llfbandit 

This is the file from iOS: https://www.metadata2go.com/result#j=78fe097a-fa95-486b-a123-3b038666239c
This is the file from Android: https://www.metadata2go.com/result#j=af20d2f7-8af6-4334-82d9-1ee53b4f88e7

The Android file get's recognized as a Video file. Perhaps that's why it's unreadable with an audio decoder

Try using the android Emulator to reproduce the issue.

**Comment by llfbandit** [comment] 2024-02-20 18:17
Please, send me the files.

**Comment by blok5025** [comment] 2024-02-20 19:03
@llfbandit https://drive.google.com/drive/folders/1oQvPVYPf406q6BuCup-Dn1iPby4aBKFQ?usp=sharing

Please confirm once you have downloaded the files.

**Comment by blok5025** [comment] 2024-02-20 19:20
From my understanding MP4 is the video format of MPEG-4 while M4A is the audio format. Is it possible that the Android encoder is not working properly? Because iOS gives us M4A files and not MP4

**Comment by blok5025** [comment] 2024-02-20 20:43
To whomever is using this package and ```audioplayers``` while fetching data from Firebase Storage. I was able to fix this issue in ```^5.0.4``` by passing the metadata manually with the file because, for some unknown reason, Firebase is not able to understand the file format of the Android Encoded file and without a File extension, the files are unreadable on iOS. (See [Troubleshoot](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md))

**Closed** 2024-03-07 07:56 UTC
Labels: Android

**Comment by Shawn-sudo** [comment] 2024-03-21 23:21
@llfbandit I have an example file here:
https://drive.google.com/file/d/1Upa2y9py4yeOgzehWXl1jzCZa0gu9pkV/view?usp=sharing
- On Google Drive, you'll be able to play it, but the seek bar doesn't behave well
  - I noticed the exact same behavior on my Android S9
- If you download the file on a macBook, you won't be able to play it
  - Same thing happens on my iPhone

**Comment by llfbandit** [comment] 2024-03-22 01:32
Could someone test with current code of `record_android` on git?

**Comment by shichunlei** [comment] 2024-05-27 08:51
I still have this problem in record: ^5.1.0. How did you solve it?

**Comment by utkudenis** [comment] 2024-06-17 16:46
Hi everyone, 
I'm still using record 4.4.4 because of the problem on this issue. 

Is there any garantee for the 5.1.1 

Because of the recording our app main feature, I cannot get risk to update package version. 
However, I need to update record with new flutter version requirement and dependencies

**Comment by utkudenis** [comment] 2024-07-05 11:13
@Shawn-sudo , @shichunlei , @llfbandit and @blok5025  can you share how is going on last version of the record package 5.1.2 ? 
i need to update my package 4.4.4 to 5.1.2

**Comment by utkudenis** [comment] 2024-10-09 13:35
hi @arreshashikant , How did you solve the problem. Can you update package to latest version without problem ?
