### ISSUE TITLE
Lost connection to the device when audiorecorder.start method is called

### ISSUE THREAD

**Issue by Stexjy** [llfbandit/record#261] opened 2023-12-17 12:20 UTC
**Package version**
5.0.1

**Environment**
Windows

**Describe the bug**
I get the Lost connection to device message when I call the start method on an instance of audio recorder

I used the default RecordConfig().

Here is the code

The widget built in the runapp method
`@override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          child: ElevatedButton(
            child: Container(
              color: Colors.black,
            ),
            onPressed: () => SST().run(),
          ),
        ),
      ),
    );
  }`

The SST run method
`Future<void> run() async {
    var record = AudioRecorder();

    await record.start(const RecordConfig(), path: path);
    await Future.delayed(const Duration(seconds: 1));
    await record.stop();
    print("Prova");
  }`

**Comment by llfbandit** [comment] 2023-12-17 19:23
A fix has been released in record 5.0.2 aside record_windows 1.0.2 as an attempt.
Marking this issue as a duplicate of #249

**Closed by llfbandit** 2023-12-17 19:23 UTC

**Comment by dorklord23** [comment] 2024-02-21 14:55
I'm using record 5.0.4 and still face the same issue.
