### ISSUE TITLE
Record to byte array(Uint8List)

### ISSUE THREAD

**Issue by pavelprosto94** [llfbandit/record#22] opened 2021-07-19 18:17 UTC
I'm using web version. I can record only virtual file. Then I need finalized record and then load virtual file to byte array(Uint8List). It takes time. Although I could play and send the file already during recording. How can this process be optimized?

**Comment by llfbandit** [comment] 2021-07-19 22:12
Currently there is no alternative. The package is not ready to include this kind of feature and it is not as simple as it sounds like. 

Quick notes:
1/ Android & iOS implementations to keep features on par. I'm not sure this could be achieved (without destroying all) . 
2/ how to determine the constraint to acquire data (time, data size?).
3/ implementing could lead to many issues with `dataavailable` event (browser impl, size of recording, . . . )

**Comment by fabiotavares** [comment] 2021-11-07 22:03
(ios and android)
How to save the file on the device?

**Comment by 3215466800** [comment] 2021-11-26 09:24
> also I have this problem can't get uint8list from recorder

me too

**Comment by llfbandit** [comment] 2021-11-26 09:45
@3215466800 @kamyar75 This is not the same issue.
Anyway, the following code should do it: `final bytes = await XFile(path).readAsBytes();`. This is also fully compliant with web target.

**Comment by 3215466800** [comment] 2021-11-26 09:51
> @3215466800 @kamyar75 This is not the same issue. Anyway, the following code should do it: `final bytes = await XFile(path).readAsBytes();`. This is also fully compliant with web target.

xfile is not support web...

**Comment by llfbandit** [comment] 2021-11-26 09:57
Yes it does https://pub.dev/packages/cross_file

**Comment by 3215466800** [comment] 2021-11-26 09:57
> Yes it does https://pub.dev/packages/cross_file

are you is record owner?

**Comment by 3215466800** [comment] 2021-11-26 09:59
i have see the code
`      final blob = html.Blob(_chunks);
      audioUrl = html.Url.createObjectUrl(blob);
`
but now i want upload this radio but now i don't know how to do

**Comment by 3215466800** [comment] 2021-11-26 10:04
> Yes it does https://pub.dev/packages/cross_file

yes i install cross_file is work already thanks

**Comment by Teajayy007** [comment] 2022-03-03 18:52
So here is a working solution to to get Uint8List for web:

 I have not confirmed this yet, but you should get the same result for mobile i hope

 final RecordPluginWeb _recordWeb = RecordPluginWeb();

when you call stop like so: _recordWeb.stop(); it returns a path string so do this 

'_recordWeb.stop().then((value) async{
final result = await http.get(Uri.parse(value));
Uint8List data = result.bodyBytes.buffer;
}`

;)

**Comment by gabrieluca** [comment] 2022-07-19 20:00
> @3215466800 @kamyar75 This is not the same issue. Anyway, the following code should do it: `final bytes = await XFile(path).readAsBytes();`. This is also fully compliant with web target.

I can't make this work, neither the following HTTP solution:
```dart
'_recordWeb.stop().then((value) async{
final result = await http.get(Uri.parse(value));
Uint8List data = result.bodyBytes.buffer;
}`
```

The result is converted into _NativeUint8List_ but it can't be uploaded through MultipartFile, while on mobile it does.

**Comment by esenmx** [comment] 2022-11-23 13:54
This would be great. I believe exposing the byte stream instead of the record file is much better.
In my case, I'm sending short audio clips over socket without persisting. Saving data to file and reading it each time means extra ms delay I don't want and I have to delete the file each time also.

**Comment by cddqssc** [comment] 2022-12-08 23:51
> This would be great. I believe exposing the byte stream instead of the record file is much better. In my case, I'm sending short audio clips over socket without persisting. Saving data to file and reading it each time means extra ms delay I don't want and I have to delete the file each time also.

Totally agree, stream is really important to audio recording.

**Comment by netapy** [comment] 2023-01-07 09:02
Heyy any news on this? It would be very useful.

**Comment by llfbandit** [comment] 2023-01-07 21:25
What I guess is that most users want the encoded output as a live stream.
This will require a lot of rework to achieve this.

Many formats are not directly streamable because of two things: headers and "chunk to chunk" encoding.
Here are the formats that should be available for streaming : AAC (in MP4 container) and PCM formats. Opus and vorbis certainly.

=> We can't stream an output that is re-written at different positions. So we can't simply watch the output file and provide chunks as soon they are written (it may or may not work at all on different platforms and versions).

So the way to go is to get closer to the codecs from the underlying platforms to access to the vended/valid chunks.

Here are my current leads on the subject:
On Android, with `MediaCodec`.
On macOS, with `AVCaptureAudioDataOutput`.
On iOS, maybe by reworking the code to use the pretty much same code as macOS.
On web, I don't know.
On Windows/linux, this seems to be a nogo with fmedia.

I started to document myself to allow this feature but don't be in a rush...

**Comment by llfbandit** [comment] 2023-06-05 10:44
Closing this in favor of #140

**Closed by llfbandit** 2023-06-05 10:44 UTC
Labels: enhancement
