### ISSUE TITLE
File doesn't exists in Windows.

### ISSUE THREAD

**Issue by SatishGD9** [llfbandit/record#199] opened 2023-08-25 12:42 UTC
**Package version**
4.4.4

**Describe the bug**
When I stop the recording the file doesn't exist in the given path, this is not happening continuously only once in a while it is happening.

**To Reproduce**
1. Start the recording.
2. Stop the recording.
3. Delete the file from the path.
4. Start the recording again.
5.  Unhandled Exception: PlatformException(WindowsAudioError, Error setting url to 'C:\Users\-\AppData\Local\Temp\6b713b3.wav'., false, null)

(Only once in a while the file will not be available in the given location and gives the above error)

**Expected behavior**
Should create the file in the specified location.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 10

**Additional context**
As I mentioned the issue is happening once in a while, when I perform the steps repeatedly.

Also I want to mention one more issue here , recorder is working only for  wav encoder in windows application.

**Comment by shubhexists** [comment] 2023-08-29 20:42
Hi, i am also trying to implement recording, the issue is that I am not getting the file at the location anytime. Can you please help me with the code snippets you used?

**Comment by ekalosak** [comment] 2023-09-03 16:25
@SatishGD9 it couldn't be as simple as a typo in your path, could it? `C:\Users-\` looks wrong to me.

**Comment by SatishGD9** [comment] 2023-09-05 08:02
> @SatishGD9 it couldn't be as simple as a typo in your path, could it? `C:\Users-\` looks wrong to me.

No there is nothing wrong in path,
it is
C:\Users\{{UserName}}\AppData\Local\Temp\6b713b3.wav

**Comment by shubhexists** [comment] 2023-09-05 11:23
I got it.
Actually the error in Android that I was getting is that I cant have a colon in a file name : ( . Took me 3 days to figure this out

**Comment by llfbandit** [comment] 2023-09-11 20:22
So we can close this?

**Closed** 2023-09-25 10:30 UTC
