### ISSUE TITLE
'Input device not found' on ios simulator

### ISSUE THREAD

**Issue by alexobviously** [llfbandit/record#164] opened 2023-06-07 11:05 UTC
**Package version**
5.0.0-beta.1

**Describe the bug**
When calling `startStream()`, running on the ios simulator, the operation fails with `PlatformException(record, Failed to start recording, Input device not found., null)`.
Presumably occurs [here](https://github.com/llfbandit/record/blob/master/record_darwin/darwin/Classes/Recorder.swift#L205https://github.com/llfbandit/record/blob/master/record_darwin/darwin/Classes/Recorder.swift#L205)

**To Reproduce**
1. Run the example app on the ios simulator
2. Encounter this error when trying to record

**Expected behavior**
It should find a device and record.

**Smartphone (please complete the following information):**
 - Device: ios simulator - iPhone 14 Pro Max
 - OS: ios 16.4

**Additional context**
It seems like the problem is that `AVCaptureDevice` might not be available on simulator https://stackoverflow.com/questions/9712382/avcapturesession-for-audio-in-simulator - this is a super super old issue but as usual there are no docs about this from apple and it's all I could find.
I'm not an ios or swift expert so I don't have a solution, but maybe you or someone else does? I'll also ask in the ios dev discord and report back if I get any useful info.

**Comment by llfbandit** [comment] 2023-06-07 12:12
I don't know how to workaround this even there is one solution to this situation.
We must add an input before running the session.

For your proposal, this is a nogo.
I guess this is just the same and `microphone` is in beta so ios>=17 and macOS>=14.

Plus the issue is located here for iOS:
https://github.com/llfbandit/record/blob/4ad9b07ae0251bac31d3eb50015bb88f8e5775aa/record_darwin/darwin/Classes/Recorder.swift#L258

**Comment by vietstone-ng** [comment] 2023-06-25 17:11
It seem AVCaptureDevice/AVCaptureSession is not supported in Simulator.
But AVAudioRecorder/AVAudioSession is supported.
Some people say this on Stackoverflow, like this one:

**Comment by llfbandit** [comment] 2023-06-25 21:50
Unless someone has a workaround. This won't be fixed.

**Closed by llfbandit** 2023-06-25 21:50 UTC
Labels: wontfix
