### ISSUE TITLE
Crash on Android - java.lang.RuntimeException - Reading of audio buffer failed: AudioRecord.ERROR_INVALID_OPERATION

### ISSUE THREAD

**Issue by patelnirav48** [llfbandit/record#158] opened 2023-05-25 04:35 UTC
Package version - record 4.4.4

Fatal Exception: java.lang.RuntimeException
Reading of audio buffer failed: AudioRecord.ERROR_INVALID_OPERATION

com.llfbandit.record.AudioRecorder$RecordDataWriter.run (AudioRecorder.java:244)

 - Device: Vivo
 - OS: Android 13

**Comment by llfbandit** [comment] 2023-06-05 10:46
Duplicate of #135

**Closed by llfbandit** 2023-06-05 10:46 UTC
