### ISSUE TITLE
Reading of audio buffer failed: AudioRecord.ERROR_INVALID_OPERATION

### ISSUE THREAD

**Issue by chiu14578** [llfbandit/record#135] opened 2023-02-16 03:09 UTC
**Package version**
4.4.4

**Describe the bug**
some devices catch error by record start AudioEncoder.pcm16bit but work by AudioEncoder.aacLc
java.lang.RuntimeException: Reading of audio buffer failed: AudioRecord.ERROR_INVALID_OPERATION

**Comment by patelnirav48** [comment] 2023-05-25 04:38
@chiu14578 Do you find any solution for this? for some devices its crashing.

**Comment by llfbandit** [comment] 2023-06-05 10:46
Another try with 5.0.0-beta.1 ?

**Comment by patelnirav48** [comment] 2023-06-05 10:47
@llfbandit Is it resolved in 5.0.0-beta.1? can i try to test in that?

**Comment by llfbandit** [comment] 2023-06-05 10:51
Yes please, I really need feedbacks as I don't reproduce it.

**Comment by patelnirav48** [comment] 2023-06-05 10:58
Actually it's specific to device like Vivo (Android OS 12, 13). It's crashing after we record 5-6 audio.

**Comment by patelnirav48** [comment] 2023-06-05 11:22
![Screenshot 2023-06-05 at 4 48 59 PM](https://github.com/llfbandit/record/assets/1640319/86a22d36-5e1d-4576-ba03-d57048935f41)

Getting this error with 5.0.0-beta.1, when we run for iOS.

**Comment by llfbandit** [comment] 2023-06-05 11:55
It's symbolic link... confirming this with published version. Was working with overriden deps while under development.

**Comment by llfbandit** [comment] 2023-06-05 13:41
darwin package has been updated to 5.0.0-beta.1+3. Don't know why symlinks are not working.

**Comment by patelnirav48** [comment] 2023-06-05 13:42
Thanks, I had tried doing manually and got below error. What i need to pass in inputdevice?

Unhandled Exception: PlatformException(record, Failed to start recording, Input device not found., null)

**Comment by llfbandit** [comment] 2023-06-05 13:48
On Android & iOS, just skip it.
If you are on simulator, it does not work.

**Comment by alexobviously** [comment] 2023-06-06 06:43
> On Android & iOS, just skip it.
> If you are on simulator, it does not work.

Hey, just wondering - is there a plan to fix this for simulator, and what's the status of that? I just came here to report the same bug (`Input device not found`).
Just trialing this package for audio input streaming in an app, and since I do most of my dev testing in the ios simulator, it's pretty important to me, but I can totally get by testing on a physical android device for now if this seems like something that can eventually be fixed.

(I'm also happy to help if I can)

**Comment by llfbandit** [comment] 2023-06-06 11:29
@alexobviously Please fill another issue for this.
The current issue is about PCM reading on Android with specific devices.

**Comment by patelnirav48** [comment] 2023-06-06 11:32
@llfbandit Have tested with Vivo device (Android 13) and working fine with latest version. Thank you very much for prompt action.

**Comment by llfbandit** [comment] 2023-06-06 11:34
That's really good news!

**Closed by llfbandit** 2023-06-06 11:34 UTC
